challenge_id = "check-floating"

challenge_name = "Check Floating"

challenge_description = '''
Infinite money glitch!
'''

challenge_spoilers = '''
Simple infinite money generator based on floating-point rounding error.
When you subtract a number from a big float, it can be below precision limits
and have no effect, but can still have an effect on a smaller float.

So, transfer nextafter(acc1, 0)/2.0f (ish) money from one account to another
and generate infinite money in the process. There's a convenient "how many times"
option to save players from needing to send 100 million packets to the server.

And yes, it is roughly 8 million transactions to make use of all the rounding error.

You have to redistribute the funds a couple times to let the error build up enough
to actually hit the goal of 1 million.
'''

author = "glenns"

hints = [
    "Use floating point rounding error to generate infinite money",
    "Somewhere around nextafter(100, 0)/2 and do like 8 million transactions. Then scale up"
]
