challenge_id = "alt-uni"

challenge_name = "Alternate Universe"

challenge_description = '''
One day you wake up and everything looks the same, but one thing is different
'''

challenge_spoilers = '''
Stack goes wrong way
'''

author = "seeinglogic"

hints = [
    "The stack is growing the wrong way, but standard approaches still work",
    "There's a stack cookie that stops you from writing too far, stop before you overwrite it."
]
