challenge_id = "anticompression"

challenge_name = "Anticompression"

challenge_description = '''
TODO: create a description here for
the challenge that is really cool
and interesting
'''

challenge_spoilers = '''
TODO: explain the challenge
here for the commentators
so that they can talk about it
'''

author = "rusty"

hints = [
    "run length encoding makes the compressed output larger than the input",
    "pwntools' cyclic(0x400) triggers the overflow"
]
