challenge_id = "trie-again"

challenge_name = "Trie Again"

challenge_description = '''
TODO: create a description here for
the challenge that is really cool
and interesting
'''

challenge_spoilers = '''
TODO: explain the challenge
here for the commentators
so that they can talk about it
'''

author = "negasora"

hints = [
    "The genie stores his knowledge in a trie, and his memory only has so much space",
    "You need to dump the contents of the trie by filling the memory and then trying to add an entry that will add one node"
]
