challenge_id = "try-harder"

challenge_name = "Try Harder"

challenge_description = '''
Come check out the latest advancements in C code control flow.
'''

challenge_spoilers = '''
The binary implements a simple stack-based VM.
The control flow of the VM dispatch loop is implemented using exceptions4c (https://github.com/guillermocalvo/exceptions4c) which uses longjmps.
The program inside the VM is a simple loop that checks the flag one character at a time starting from the back. 
'''

author = "ZetaTwo"

hints = [
    "The flag is checked from back to front",
    "Instruction counting should work"
]
