challenge_id = "executable-image"

challenge_name = "Executable Image"

challenge_description = '''
TODO: create a description here for
the challenge that is really cool
and interesting
'''

challenge_spoilers = '''
TODO: explain the challenge
here for the commentators
so that they can talk about it
'''

author = "rusty"

hints = [
    "TODO: This is hint one",
    "TODO: This is the second hint"
]
